### ISSUE TITLE
Conform to database/sql/driver interfaces

### ISSUE THREAD

**Issue by ricardoseriani** [rowland/go-fb#2]
Hi

I know that in README.md has said:  `Firebird package for Go. Does not currently conform to database/sql/driver interfaces.`, but there's any schedule to do so ?
And If not, there is a way to add/support Prepared Statement ?

Thanks in advance

**Comment by rowland** [comment]
https://github.com/nakagami/firebirdsql gets you both, with the added benefit that it's pure Go. The primary downside the last time I used it was that long-running connections appeared to hold open a transaction, blocking garbage collection. I'm hopeful this changes soon, if it hasn't already.

**Comment by ricardoseriani** [comment]
Hmm, I know, but the problem is that I'm having some issues (https://github.com/nakagami/firebirdsql/issues/30), and with your package, it's running OK.

**Comment by rowland** [comment]
At this point, I do not foresee go-fb ever supporting the database/sql/driver interface. It would be nice to have a compliant package that also uses the native driver, for whatever advantages it provides, but I cannot justify the investment of time when the nakagami package is available. Sorry.
